"""Gather the folded complexes for figure-making: flat filenames, a manifest, and a PyMOL script.

Three problems this solves:

* the structures are buried at `boltz/boltz_results_<name>/predictions/<name>/<name>_model_0.cif`,
  which is tedious to load twelve of;
* several of the results are counterintuitive enough to be mis-captioned from memory -- esm2 has the
  strongest interaction energy of the three sequences and wraps the *least* of them -- so the
  manifest puts each structure's numbers next to its filename;
* the folds arrive in Boltz's frame, so comparing how differently each one wraps the ligand needs
  them superposed on the ligand first, which the generated script does.

On comparing a fold with the **designed shell**: that is a different superposition, because the
shell's `.xyz` carries no atom names for PyMOL to match on. `overlay.py --save-overlays` already
does that numerically and writes the superposed complexes, so use those rather than trying to align
the raw files in PyMOL.

Usage:
    python code/make_figures.py runs/octinoxate
    pymol runs/octinoxate/figures/load_folds.pml
"""
import argparse
import csv
import glob
import os
import shutil
import sys

PML_HEADER = """# Generated by code/make_figures.py -- edit freely, it is only a starting point.
# Every fold is superposed on its ligand, so differences you see are differences in how the
# peptide sits around it rather than differences in viewpoint.

# The loads below are relative, so the script sets its own directory first. Without this, running
# it from anywhere else fails every load, and PyMOL carries on to leave an empty session whose
# only symptom is `Invalid selection name` later on.
cd {figdir}

# No `reinitialize` and no background colour: your .pymolrc defaults should win. Run this into a
# fresh session if you want a clean slate.
set stick_radius, 0.15
set sphere_scale, 0.22
"""

PML_FOOTER = """
# --- representations --------------------------------------------------------------------------
# No cartoon: a ribbon through the backbone reads as extra bulk next to the atoms being judged.
# Sticks throughout -- mixing lines and sticks by proximity looked like a rendering glitch.
# Note these structures are heavy-atom only: Boltz writes no hydrogens.
hide everything
show sticks
# green peptide, red ligand: both read well on a dark background, where grey does not
color green, polymer
color red, not polymer

# the designed shell, if loaded: ligand plus the placed fragments, i.e. what was asked for.
# It is in its own frame, not superposed with the folds.
show sticks, shell
color marine, shell

# default axis-aligned orientation rather than a hard-coded or auto-oriented one
reset
zoom not polymer, 8

# --- one set at a time ------------------------------------------------------------------------
# Loaded in reading order: control, f4, f8, f12 for each sequence set in turn. To compare a pair:
#   disable all
#   enable {first}
#   enable {second}
# (one per line: PyMOL splits on a semicolon even inside a comment, so a hint written
# on one line would execute its own tail)
#
# The name below is the first fold actually loaded, not a fixed one. It used to be hard-coded to
# shell 1's `orig_control`, so a second shell's script disabled everything and then enabled an
# object that did not exist -- opening it showed an empty window with no error worth reading.
disable all
enable {first}
"""

# Representation only, no loads and no alignment, so it can be applied to whatever is in the session:
#   @style.pml
# Written only when absent, so a hand-tuned copy is never overwritten.
#
# Note for anyone editing this: PyMOL splits commands on a semicolon even inside a comment, so text
# following one is executed as a command. Never put that character in this file.
STYLE_PML = """# Representation only. No loads, no alignment.
# Run it after loading whatever you want:  @style.pml

set auto_show_cartoon, 0
set auto_show_lines, 0

hide everything
show sticks

bg_color black
color green, polymer
color red, not polymer
set stick_radius, 0.15

# yellow reads cleanly against black, green and red at once.
# A negative label_size is in Angstroms rather than screen points, so the text scales with the
# molecule instead of staying the same size as you zoom out.
set label_size, -0.7
set label_color, yellow

# every residue, on CA only, so one label per residue rather than one per atom
label polymer and name CA, resn+resi

# No zoom: your current view is probably the one you want. Type "zoom polymer" if you want the
# whole thing framed.
#
# Adjustments, to type at the prompt:
#   set label_size, -0.5      smaller, still scaling with zoom
#   set label_size, -1.0      larger, still scaling with zoom
#   set label_color, wheat
#   label none
"""


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("outdir")
    parser.add_argument("--ligand", default="octinoxate")
    parser.add_argument("--design-sequence", default="RGGDGGKGGGGLGGGGKGIGEGWGGDGSGGEGS",
                        help="the design whose shell .xyz to include as the reference")
    parser.add_argument("--fig-dir", default="figures",
                        help="output directory inside outdir (default figures). Give a second shell "
                             "its own, or it overwrites the first shell's manifest and script")
    parser.add_argument("--match",
                        help="only include folds whose name contains this, e.g. s2_ for a second "
                             "shell. Without it every fold under boltz/ is gathered")
    args = parser.parse_args(argv)

    boltz_dir = os.path.join(args.outdir, "boltz")
    fig_dir = os.path.join(args.outdir, args.fig_dir)
    os.makedirs(fig_dir, exist_ok=True)

    # Numbers, keyed by structure name, from every results csv present. This is a glob rather than a
    # list of filenames because the list went stale: it named a `binding_a.csv` that does not exist
    # and omitted `binding_esm2f.csv`, so re-running this script would have silently blanked the
    # esm2 interaction and strain columns of a manifest that was correct on disk. Each scoring run
    # writes its own csv under a name of its own choosing, so matching the pattern is the only way
    # to stay correct as runs accumulate.
    numbers = {}
    for path in sorted(glob.glob(os.path.join(boltz_dir, "fold_check*.csv"))
                       + sorted(glob.glob(os.path.join(boltz_dir, "binding_*.csv")))):
        with open(path) as fh:
            for row in csv.DictReader(fh):
                numbers.setdefault(row["name"], {}).update(
                    {k: v for k, v in row.items() if v not in ("", None)})

    cifs = sorted(glob.glob(os.path.join(boltz_dir, "boltz_results_*", "predictions", "*",
                                         "*_model_0.cif")))
    if args.match:
        cifs = [c for c in cifs if args.match in os.path.basename(c)]
    if not cifs:
        sys.exit(f"no folded complexes under {boltz_dir}"
                 + (f" matching {args.match!r}" if args.match else ""))

    long_name = args.design_sequence
    SETS = {"orig": 0, "esm1": 1, "esm2": 2}
    VARIANTS = {"control": 0, "f4": 1, "f8": 2, "f12": 3}

    def order(short):
        """control -> f4 -> f8 -> f12, grouped by sequence set: the order to read them in.

        A shell prefix (`s2_orig_f4`) is stripped before the set and variant are read, so a second
        shell's ladder reads in the same order as the first's rather than collapsing to
        alphabetical. The prefix stays the leading sort key, keeping each shell's folds together.
        """
        shell, rest = "", short
        grp, _, var = rest.partition("_")
        if grp not in SETS and var:
            shell, rest = grp, var
            grp, _, var = rest.partition("_")
        return shell, SETS.get(grp, 9), VARIANTS.get(var, 9), short

    manifest, loads = [], []
    for cif in cifs:
        full = os.path.basename(cif).replace("_model_0.cif", "")
        # `<design>_esm1` is esm1's *unconstrained control*, not an orig variant -- the fold names
        # collide confusingly, so normalise to <set>_<variant> with the set first.
        short = full.replace(long_name + "_", "").replace(long_name, "orig")
        if short in ("esm1", "esm2"):
            short = short + "_control"
        elif short == "control":
            short = "orig_control"
        elif short.startswith("f"):
            short = "orig_" + short
        dest = os.path.join(fig_dir, short + ".cif")
        shutil.copy(cif, dest)
        loads.append((order(short), f"load {short}.cif, {short}"))
        n = numbers.get(full, {})
        manifest.append({
            "figure_name": short, "file": short + ".cif", "structure": full,
            "enclosed_fraction": n.get("enclosed_fraction", ""),
            "wrapped_fraction": n.get("wrapped_fraction", ""),
            "centroid_separation": n.get("centroid_separation", ""),
            "engaged": (f"{n.get('engaged','')}/{n.get('ligand_heavy_atoms','')}"
                        if n.get("engaged") else ""),
            "mean_ligand_distance": n.get("mean_ligand_distance", ""),
            "contacts_under_cutoff": n.get("contacts_under_cutoff", ""),
            "hints": (f"{n.get('hints_satisfied','')}/{n.get('n_hints','')}"
                      if n.get("n_hints") else "none applied"),
            "interaction_kcal": n.get("interaction_kcal", ""),
            "strain_ligand_kcal": n.get("strain_ligand_kcal", ""),
        })

    # Superpose the designed shell onto a fold's ligand. The shell's .xyz carries no atom names,
    # so PyMOL cannot match it -- but its first atoms are the ligand in the pipeline's own order,
    # and `boltz_hints.ligand_atom_names` gives Boltz's name for each of those. That correspondence
    # turns into an explicit pair_fit, which is what makes the comparison possible at all.
    fit_cmd = ""
    try:
        from boltz_hints import ligand_atom_names
        from boltz_check import ligand_smiles
        from peptide_builder import load_ligand
        lig = load_ligand(args.ligand if hasattr(args, "ligand") else "octinoxate")
        names = ligand_atom_names(args.outdir, ligand_smiles(args.outdir))
        ref = sorted(manifest, key=lambda r: order(r["figure_name"]))[0]["figure_name"]
        pairs = [f"shell and id {i + 1}, {ref} and name {names[i]}"
                 for i, sym in enumerate(lig["atoms"]) if sym != "H"]
        fit_cmd = ("\n# put the designed shell in the same frame as the folds, by its ligand\n"
                   "pair_fit " + ", ".join(pairs) + "\n")
        print(f"shell will be superposed onto {ref} using {len(pairs)} ligand atoms")
    except Exception as exc:
        print(f"note: could not build the shell superposition ({type(exc).__name__}: {exc}); "
              f"the shell will load in its own frame")

    shell = os.path.join(args.outdir, "sequences", long_name + ".xyz")
    if os.path.exists(shell):
        shutil.copy(shell, os.path.join(fig_dir, "designed_shell.xyz"))
        # Same shape as order() returns, or sorting compares an int against a str and raises.
        loads.insert(0, (("", -1, -1, "shell"), "load designed_shell.xyz, shell"))
        print("included the designed shell as designed_shell.xyz")
    else:
        print(f"note: no designed shell at {shell}, so the reference is not included")

    man_path = os.path.join(fig_dir, "manifest.csv")
    fields = list(manifest[0].keys())
    with open(man_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        w.writerows(sorted(manifest, key=lambda r: order(r["figure_name"])))

    pml_path = os.path.join(fig_dir, "load_folds.pml")
    with open(pml_path, "w") as fh:
        ordered = [cmd for _, cmd in sorted(loads, key=lambda t: t[0])]
        header = PML_HEADER.format(figdir=os.path.abspath(fig_dir))

        # Superpose every fold on the ligand of the first, as plain `align` lines rather than a
        # `python ... python end` block. The block was the only non-standard construct in this
        # script, and if anything inside it raised -- aligning `shell and not polymer` is one way,
        # since the shell has no polymer -- PyMOL could be left with its parser still in Python
        # mode, so the next command typed came back as "Invalid selection name" against a
        # perfectly valid object.
        names = [c.split(", ")[-1] for _, c in sorted(loads, key=lambda t: t[0])]
        names = [n for n in names if n != "shell"]
        align_lines = [
            "\n# --- superpose every fold on the ligand of the first ------------------------------",
            "# The ligands are the same molecule from the same SMILES, so they share atom names and",
            "# align cleanly. This is what makes the enclosure comparison visual.",
        ]
        for n in names[1:]:
            align_lines.append(
                f"align {n} and not polymer, {names[0]} and not polymer, cycles=0")
        align_block = "\n".join(align_lines) + "\n" if len(names) > 1 else ""

        footer = PML_FOOTER.format(first=names[0] if names else "all",
                                   second=names[-1] if len(names) > 1 else "all")
        fh.write(header + "\n" + "\n".join(ordered) + "\n" + fit_cmd + align_block + footer)

    # A representation script beside the loader, so a new figure directory is usable on its own.
    # Never overwritten: shell 1's copy may have been tuned by hand.
    style_path = os.path.join(fig_dir, "style.pml")
    if not os.path.exists(style_path):
        with open(style_path, "w") as fh:
            fh.write(STYLE_PML)
        print(f"wrote {style_path}")

    print(f"\n{len(cifs)} structures copied to {fig_dir}")
    print(f"manifest -> {man_path}")
    print(f"pymol    -> {pml_path}\n")
    print(f"{'figure name':<16} {'enclosed':>9} {'wrapped':>8} {'inter':>8} {'strain':>8} "
          f"{'sum':>8} {'hints':>13}")
    for r in sorted(manifest, key=lambda r: order(r["figure_name"])):
        i, st = r["interaction_kcal"], r["strain_ligand_kcal"]
        tot = f"{float(i) + float(st):.2f}" if i and st else ""
        print(f"{r['figure_name']:<16} {r['enclosed_fraction']:>9} {r['wrapped_fraction']:>8} "
              f"{i:>8} {st:>8} {tot:>8} {r['hints']:>13}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
