# Generated by code/make_figures.py -- edit freely, it is only a starting point.
# Every fold is superposed on its ligand, so differences you see are differences in how the
# peptide sits around it rather than differences in viewpoint.

# The loads below are relative, so the script sets its own directory first. Without this, running
# it from anywhere else fails every load, and PyMOL carries on to leave an empty session whose
# only symptom is `Invalid selection name` later on.
cd /Users/cafierom/python_mac/peptidebuilder/runs/octinoxate/figures_shell2

# No `reinitialize` and no background colour: your .pymolrc defaults should win. Run this into a
# fresh session if you want a clean slate.
set stick_radius, 0.15
set sphere_scale, 0.22

load designed_shell.xyz, shell
load s2_orig_control.cif, s2_orig_control
load s2_orig_f4.cif, s2_orig_f4
load s2_orig_f8.cif, s2_orig_f8
load s2_orig_f12.cif, s2_orig_f12
load s2_esm1_control.cif, s2_esm1_control
load s2_esm1_f4.cif, s2_esm1_f4
load s2_esm1_f8.cif, s2_esm1_f8
load s2_esm1_f12.cif, s2_esm1_f12
load s2_esm2_control.cif, s2_esm2_control
load s2_esm2_f4.cif, s2_esm2_f4
load s2_esm2_f8.cif, s2_esm2_f8
load s2_esm2_f12.cif, s2_esm2_f12

# put the designed shell in the same frame as the folds, by its ligand
pair_fit shell and id 1, s2_orig_control and name C35, shell and id 2, s2_orig_control and name C31, shell and id 3, s2_orig_control and name C33, shell and id 4, s2_orig_control and name C36, shell and id 5, s2_orig_control and name C34, shell and id 6, s2_orig_control and name C32, shell and id 11, s2_orig_control and name O26, shell and id 12, s2_orig_control and name C37, shell and id 16, s2_orig_control and name C30, shell and id 18, s2_orig_control and name C29, shell and id 20, s2_orig_control and name C28, shell and id 21, s2_orig_control and name O25, shell and id 22, s2_orig_control and name O27, shell and id 23, s2_orig_control and name C44, shell and id 25, s2_orig_control and name C43, shell and id 28, s2_orig_control and name C42, shell and id 31, s2_orig_control and name C39, shell and id 35, s2_orig_control and name C41, shell and id 38, s2_orig_control and name C40, shell and id 41, s2_orig_control and name C38

# --- superpose every fold on the ligand of the first ------------------------------
# The ligands are the same molecule from the same SMILES, so they share atom names and
# align cleanly. This is what makes the enclosure comparison visual.
align s2_orig_f4 and not polymer, s2_orig_control and not polymer, cycles=0
align s2_orig_f8 and not polymer, s2_orig_control and not polymer, cycles=0
align s2_orig_f12 and not polymer, s2_orig_control and not polymer, cycles=0
align s2_esm1_control and not polymer, s2_orig_control and not polymer, cycles=0
align s2_esm1_f4 and not polymer, s2_orig_control and not polymer, cycles=0
align s2_esm1_f8 and not polymer, s2_orig_control and not polymer, cycles=0
align s2_esm1_f12 and not polymer, s2_orig_control and not polymer, cycles=0
align s2_esm2_control and not polymer, s2_orig_control and not polymer, cycles=0
align s2_esm2_f4 and not polymer, s2_orig_control and not polymer, cycles=0
align s2_esm2_f8 and not polymer, s2_orig_control and not polymer, cycles=0
align s2_esm2_f12 and not polymer, s2_orig_control and not polymer, cycles=0

# --- representations --------------------------------------------------------------------------
# No cartoon: a ribbon through the backbone reads as extra bulk next to the atoms being judged.
# Sticks throughout -- mixing lines and sticks by proximity looked like a rendering glitch.
# Note these structures are heavy-atom only: Boltz writes no hydrogens.
hide everything
show sticks
# green peptide, red ligand: both read well on a dark background, where grey does not
color green, polymer
color red, not polymer

# the designed shell, if loaded: ligand plus the placed fragments, i.e. what was asked for.
# It is in its own frame, not superposed with the folds.
show sticks, shell
color marine, shell

# default axis-aligned orientation rather than a hard-coded or auto-oriented one
reset
zoom not polymer, 8

# --- one set at a time ------------------------------------------------------------------------
# Loaded in reading order: control, f4, f8, f12 for each sequence set in turn. To compare a pair:
#   disable all
#   enable s2_orig_control
#   enable s2_esm2_f12
# (one per line: PyMOL splits on a semicolon even inside a comment, so a hint written
# on one line would execute its own tail)
#
# The name below is the first fold actually loaded, not a fixed one. It used to be hard-coded to
# shell 1's `orig_control`, so a second shell's script disabled everything and then enabled an
# object that did not exist -- opening it showed an empty window with no error worth reading.
disable all
enable s2_orig_control
