# Generated by code/make_figures.py -- edit freely, it is only a starting point.
# Every fold is superposed on its ligand, so differences you see are differences in how the
# peptide sits around it rather than differences in viewpoint.

# No `reinitialize` and no background colour: your .pymolrc defaults should win. Run this into a
# fresh session if you want a clean slate.
set stick_radius, 0.15
set sphere_scale, 0.22

load designed_shell.xyz, shell
load orig_control.cif, orig_control
load orig_f4.cif, orig_f4
load orig_f8.cif, orig_f8
load orig_f12.cif, orig_f12
load esm1_control.cif, esm1_control
load esm1_f4.cif, esm1_f4
load esm1_f8.cif, esm1_f8
load esm1_f12.cif, esm1_f12
load esm2_control.cif, esm2_control
load esm2_f4.cif, esm2_f4
load esm2_f8.cif, esm2_f8
load esm2_f12.cif, esm2_f12

# put the designed shell in the same frame as the folds, by its ligand
pair_fit shell and id 1, orig_control and name C35, shell and id 2, orig_control and name C31, shell and id 3, orig_control and name C33, shell and id 4, orig_control and name C36, shell and id 5, orig_control and name C34, shell and id 6, orig_control and name C32, shell and id 11, orig_control and name O26, shell and id 12, orig_control and name C37, shell and id 16, orig_control and name C30, shell and id 18, orig_control and name C29, shell and id 20, orig_control and name C28, shell and id 21, orig_control and name O25, shell and id 22, orig_control and name O27, shell and id 23, orig_control and name C44, shell and id 25, orig_control and name C43, shell and id 28, orig_control and name C42, shell and id 31, orig_control and name C39, shell and id 35, orig_control and name C41, shell and id 38, orig_control and name C40, shell and id 41, orig_control and name C38

# --- superpose everything on the ligand of the first fold -------------------------------------
# The ligands are all the same molecule from the same SMILES, so they share atom names and align
# cleanly. This is what makes the enclosure comparison visual.
python
from pymol import cmd
objs = [o for o in cmd.get_names("objects") if o != "shell"]
if objs:
    ref = objs[0]
    for o in objs[1:]:
        cmd.align(f"{o} and not polymer", f"{ref} and not polymer", cycles=0)
python end

# --- representations --------------------------------------------------------------------------
# No cartoon: a ribbon through the backbone reads as extra bulk next to the atoms being judged.
# Sticks throughout -- mixing lines and sticks by proximity looked like a rendering glitch.
# Note these structures are heavy-atom only: Boltz writes no hydrogens.
hide everything
show sticks
# green peptide, red ligand: both read well on a dark background, where grey does not
color green, polymer
color red, not polymer

# the designed shell, if loaded: ligand plus the placed fragments, i.e. what was asked for.
# It is in its own frame, not superposed with the folds.
show sticks, shell
color marine, shell

# default axis-aligned orientation rather than a hard-coded or auto-oriented one
reset
zoom not polymer, 8

# --- one set at a time ------------------------------------------------------------------------
# Loaded in reading order: control, f4, f8, f12 for orig, then esm1, then esm2. To compare a pair:
#   disable all ; enable orig_control ; enable orig_f12
disable all
enable orig_control
enable shell
